import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sidebar";

// Import the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

/**
 * Metadata for the root layout.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

/**
 * Root layout component.
 *
 * @param {ReactNode} children - The content to be rendered within the layout.
 * @returns {JSX.Element}
 */

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative container mx-auto max-w-7xl z-10 px-6 min-h-[calc(100vh_-_64px_-_108px)] mb-12">
          <div className="grid grid-cols-12 gap-4 my-10">
            <div className="col-span-2">
              <Sidebar />
            </div>
            <div className="col-span-10">{children}</div>
          </div>
        </main>
        <footer className="bg-default-800 text-white py-4">
          <div className="container mx-auto text-center">
            <p>&copy; 2023-2024 My Website. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
